apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcs
spec:
  template:
    spec:
      containers:
        - image: mcs
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: OPENAI_API_KEY
                  key: latest

            - name: WORKSPACE_DIR
              valueFrom:
                secretKeyRef:
                  name: WORKSPACE_DIR
                  key: latest      

            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: MASTER_KEY
                  key: latest
          ports:
            - containerPort: 8000